name = "prescripto-frontend"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
name = "prescripto-frontend-prod"

[env.staging]
name = "prescripto-frontend-staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
